# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: realifexperience
email: seifelmejri@gmail.com
description: A virtual proof that I'm awesome.This website was designed in order to write what I could not say. It  is meant to be  a gateway of many thoughts that I would rather share than keep in mind.


#baseurl: "/Reality" # the subpath of your site, e.g. /blog
url: "http://realifexperience.com" # the base hostname & protocol for your site
twitter_username: Seif_mej
github_username:  seifedd

# Build settings
markdown: kramdown
